"""empty message

Revision ID: 3e15add81b27
Revises: 
Create Date: 2020-05-16 21:56:18.739029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e15add81b27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('sys_active', sa.Boolean(), nullable=True),
    sa.Column('sys_created', sa.DateTime(), nullable=True),
    sa.Column('sys_updated', sa.DateTime(), nullable=True),
    sa.Column('Name', sa.String(length=300), nullable=True),
    sa.Column('Description', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('sys_active', sa.Boolean(), nullable=True),
    sa.Column('sys_created', sa.DateTime(), nullable=True),
    sa.Column('sys_updated', sa.DateTime(), nullable=True),
    sa.Column('Username', sa.String(length=30), nullable=True),
    sa.Column('FirstName', sa.String(length=300), nullable=True),
    sa.Column('LastName', sa.String(length=300), nullable=True),
    sa.Column('Email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scenario')
    # ### end Alembic commands ###
